### ISSUE TITLE
Not retrieving information

### ISSUE THREAD

**Issue by tobymanders** [alexbotello/python-overwatch#6]
Can't get package to work in Python 3.7.2. Immediately after installing with PIP, I execute:

```
>>> from overwatch import Overwatch
>>> overwatch = Overwatch(battletag="Okush#11324")
>>> print(overwatch.playtime)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Toby-PC\Anaconda3\lib\site-packages\overwatch\__init__.py", line 80, in playtime
    return self._generate_comparisons(compare['playtime'])
  File "C:\Users\Toby-PC\Anaconda3\lib\site-packages\overwatch\__init__.py", line 75, in _generate_comparisons
    comparison = data[self.mode]
IndexError: list index out of range
```

None of the methods of the overwatch object seems to work. I've also tried this with multiple different battletags.

**Comment by slacksystem** [comment]
Is this likely to be addressed?
